title: Basic Command Line Interface (CLI) Configuration
pre-requisites: CONT-05_Merging-pull-requests
learning-objective: Successfully configure the CLI to be able to work effectively with Git.
screens: 
  - image-slide:
      title: Git Configuration Levels
      image: https://training.github.com/kit/assets/diagrams/git-logo-black.svg
      presenter-script:
        - If you prefer to work on the command line, you can easily integrate GitHub into your current workflow. The first thing you should do when you get started using git is to set your configuration options.
        - Git allows you to set configuration options at three different levels.
        - --system - These are system-wide configurations. They apply to all users on this computer.
        - -- global - These are the user level configurations. They only apply to your user account.
        - --local - These are the repository level configurations. They only apply to the specific repository where they are set.
        - The default value for git config is --local.
        - We will revisit our configuration setting throughout the class; right now we are only setting the essentials to get us started.
  - video-slide: 
      title: Configuring Git
      video: https://www.youtube.com/watch?v=r5C6yXNaSGo
      video-script: 
        - do: Open the CLI
          say: "Git is OS agnostic; the commands are essentially the same whether you are on Mac, Windows or Linux. You can use your favorite application to interact with the command line. Follow along with the commands in this video to make sure your computer is configured correctly."
        - do: Type `git --version` 
          say: "First, let's check the version of Git currently installed on your system. At the very least you should have a version greater than 1.9.5 installed."
        - do: Type `git config --global user.name "<user name>"` and Type `git config --global user.email "<user email>"` 
          say: "Git uses the config settings for your user name and email address to generate a unique fingerprint for each of the commits you create, so let's set our user name and email address first."
        - do: Type `git config --global core.editor "<editor path>"`
          say: "Next, we will add a default text editor. This is the text editor git will use when you need to edit things like commit messages or handle merge conflicts."
        - do: "Type `git config --global core.autocrlf [input | true ]`"
          say: "`autocrlf` stands for auto carriage return line feed. Different systems handle line endings and line breaks differently. If you open a file created on another system and do not have this config option set, git will think you made changes to the file based on the way your system handles this type of file. If you are on a Windows machine, you will want to set this option to `true`. If you are on a Mac or Linux machine, you will set it to `input`."
        - do: Type `git config --list`
          say: "If you would like to see which config settings have already been applied, you can type `git config --list`. This will automatically read from each of the storage containers for config settings and list them. You may notice duplicate settings if the same variable is set in multiple locations. The lowest value on the list takes precedence."
additional-labs: 
additional-questions:
resources: 